version: "3.5"
services:
  tvheadend:
    #image: linuxserver/tvheadend:arm32v7-version-02987438
    image: linuxserver/tvheadend:arm64v8-latest
    platform: linux/arm/v7
    container_name: tvheadend
    #user: 1001:1001
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - RUN_OPTS= #optional
    volumes:
      - /var/local/iptv/TVHeadend/data:/config
      - /var/local/iptv/TVHeadend/recordings:/recordings
    network_mode: host
    restart: unless-stopped
